#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/app

- name: Run backend application
  community.docker.docker_container:
    name: "{{ app_container_name }}"
    image: "{{ app_image }}"
    networks:
      - name: "{{ docker_network_name }}"
    env:
      DB_HOST: "{{ database_container_name }}"
      DB_PORT: "5432"
      DB_USER: "{{ database_user }}"
      DB_PASSWORD: "{{ database_password }}"
      DB_NAME: "{{ database_name }}"
    restart_policy: unless-stopped
    state: started
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python3
