#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/app

- name: Run backend application
  community.docker.docker_container:
    name: "{{ app_container_name }}"
    image: "{{ app_image }}"
    networks:
      - name: "{{ docker_network_name }}"
    env:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ database_container_name }}:5432/{{ database_name }}"
      SPRING_DATASOURCE_USERNAME: "{{ database_user }}"
      SPRING_DATASOURCE_PASSWORD: "{{ database_password }}"
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart_policy: unless-stopped
    state: started
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python3
